---
title: "assignment05"
author: "ShaeChang"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
#library all packages needed
library(tidyverse)
library(stringr)
library(readr)
library(lubridate)
library(dplyr)
library(sf)
library(ggplot2)
library(tigris)
library(patchwork)
library(tidycensus)
```

# 1.Data Loading & Cleaning 

```{r #1}
#it seems "read_csv" is better than "read.csv", but I still don't know why.
crime <- read_csv("data/crimes-reduced.csv",
                  col_types = cols(
                    Longitude = col_character(), 
                    Latitude = col_character()
                    )
                  ) %>%
  #to use another syntax seems easier, but we are asked to use "rename".
  rename(id = ID,
         date = Date,
         primary_type = `Primary Type`,
         arrest = Arrest,
         x_coordinate = `X Coordinate`,
         y_coordinate = `Y Coordinate`,
         community_area = `Community Area`,
         latitude = Latitude,
         longitude = Longitude,
         location = Location
         )
glimpse(crime)
```

# 2. Filtering the data to homicides within ten years of today

```{r #2}
crime_lim <- crime %>%
  #select crimes we are interested in
  filter(primary_type == "HOMICIDE") %>%
  filter(!is.na(latitude) | !is.na(longitude)) %>%
  mutate(
    datetime = mdy_hms(date),
    #change the unit of the duration of the time to seconds, to make the comparision later easier
    periodtime = as.duration(now() - datetime)
    ) %>%
  #filter by comparing the periodtime is longer than 10 years or not. Use "dyears" to measure the duriation also in seconds
  filter(periodtime < dyears(10))
table(
  year(crime_lim$datetime)
)
min(crime_lim$datetime)
```

# 3. Convert Lon/Lat to Points Geometry

```{r #3}
crime_limsf <- crime_lim %>%
  st_as_sf(coords = c("longitude", "latitude")) %>%
  st_set_crs(value = 4326) 

ggplot() +
  #use "alpha" to adjust the transparency of the points
  geom_sf(data = crime_limsf, mapping = aes(color = arrest, alpha=0.1)) +
  #also, make point size a bit smaller
  geom_point(size = 0.05)

```

# 4. Load Census Tracts, Perform a Spatial Join, and Create Choropleth.

```{r #4}
#read the shapefile data from .shp file downloaded
shapefile <- st_read("data/geo_export_bd405ca0-25a8-45be-9e7d-2940f7aa38f7.shp") %>%
  st_transform(4326) %>%
  select(geoid10, geometry)

#perform a spatial join, and calculate the count of homicides and the percent of arrests per homicide 
chicago = st_join(shapefile, crime_limsf)
chicago_merged_agg <- chicago%>%
  as_tibble() %>% #converting from sf to tibble
  group_by(primary_type)%>%
  group_by(geoid10)%>%
  summarise(count = n(), percent = mean(c(arrest==TRUE, TRUE, FALSE))) 

#make the tibble join a dataset with geometry
crimemap <- left_join(chicago, chicago_merged_agg, by = "geoid10")

#come out the pictures with "patchwork"
p1 <- crimemap %>%
  ggplot() +
  geom_sf(aes(fill = count)) +
  scale_fill_gradient(
    low = "#cfe8f3", 
    high = "#062635"
  ) +
  theme_void() 

p2 <- crimemap %>%
  ggplot() +
  geom_sf(aes(fill = percent)) +
  scale_fill_gradient(
    low = "#cfe8f3", 
    high = "#062635"
  ) +
  theme_void() 

p1 + p2
```

# 5. Using the Census API

```{r #5 API key}
credential <- Sys.getenv("census_api_key")
#Had an API key already, so need to overwrite it
census_api_key("a1a794c310d30ce78c5ade2702d6a46f40716e31",overwrite = TRUE, install = TRUE)
```

```{r #5 retrieve}
readRenviron("~/.Renviron")
v17 <- load_variables(2017, "acs5", cache = TRUE)
cookcounty_r <- as_tibble(
  get_acs(
    geography = "tract",
    variables = c(medianinc = "B19013_001",
                  poppov = "B17001_001",
                  popdegree = "B15003_022"),
    state = 17,
    country = 031,
    geometry = TRUE,
    year = 2017
  )
)
view(cookcounty_r)
```



